dbt_openaq:
  outputs:
    dev:
      dbname: OpenAQ_DWH
      host: localhost
      pass: '123456'
      port: 5432
      schema: production
      threads: 1
      type: postgres
      user: postgres
  target: dev
